services:
  app:
    container_name: nestjs-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.andy
    ports:
      - "3001:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=meteo
      - MONGO_INITDB_ROOT_PASSWORD=MonsUperPassAvecMaster
      - MONGO_INITDB_DATABASE=meteo

volumes:
  mongo-data: