services:

  app:
    container_name: nestjs-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.andy
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - nesjs-network

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=meteo
      - MONGO_INITDB_ROOT_PASSWORD=MonsUperPassAvecMaster
      - MONGO_INITDB_DATABASE=meteo
    networks:
      - nesjs-network

volumes:
  mongo-data:

networks:
    nesjs-network:
      driver: bridge
      name: nest_network